batch_sizes:
- 32
- 16
learning_rates:
- 1e-04
- 3e-05
- 5e-05
epochs:
- 10
context_sizes:
- 0
seeds:
- 1
layers: '-1'
subword_poolings:
- first
use_crf: false
use_tensorboard: true
cuda: '0'
task: ner
datasets:
- conll03_english
hf_model: answerdotai/ModernBERT-large
model_short_name: modern_bert_large
